-- Compatível com PostgreSQL e com H2 (MODE=PostgreSQL).

CREATE TABLE admin_usuario (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario     VARCHAR(60)  NOT NULL UNIQUE,
    senha_hash  VARCHAR(255) NOT NULL,
    criado_em   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE publicacao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR(20)  NOT NULL,
    data_hora       TIMESTAMP WITH TIME ZONE NOT NULL,
    local_endereco  VARCHAR(300) NOT NULL,
    descricao_html  TEXT         NOT NULL,
    cor_fundo       VARCHAR(7)   NOT NULL,
    criado_em       TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_publicacao_tipo CHECK (tipo IN ('PALESTRA', 'EVENTO'))
);

CREATE INDEX ix_publicacao_tipo_data ON publicacao (tipo, data_hora);

CREATE TABLE midia (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacao_id  BIGINT        NOT NULL REFERENCES publicacao (id) ON DELETE CASCADE,
    tipo           VARCHAR(20)   NOT NULL,
    url            VARCHAR(1000) NOT NULL,
    descricao      VARCHAR(500),
    ordem          INT           NOT NULL,
    CONSTRAINT ck_midia_tipo CHECK (tipo IN ('IMAGEM', 'VIDEO', 'VIDEO_LINK'))
);

CREATE INDEX ix_midia_publicacao ON midia (publicacao_id);
