-- Serviços exibidos na seção "Serviços" do site, editáveis pelo painel.
-- Os textos iniciais são os que antes ficavam fixos no código (frontend/src/app/core/seo.ts).
CREATE TABLE servico (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         VARCHAR(120)  NOT NULL,
    descricao      VARCHAR(2000) NOT NULL,
    criado_em      TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em  TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO servico (titulo, descricao, criado_em, atualizado_em) VALUES
('Intérprete de Libras e tradução simultânea',
 'Profissionais de Libras (Língua Brasileira de Sinais) fazem a interpretação simultânea de palestras, congressos, seminários, aulas, reuniões, cerimônias, shows e eventos corporativos. A pessoa surda acompanha tudo em tempo real, junto com o restante do público.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO servico (titulo, descricao, criado_em, atualizado_em) VALUES
('Libras em eventos online e lives',
 'Interpretação em Libras para transmissões ao vivo, webinars e reuniões em Zoom, Microsoft Teams, Google Meet e YouTube, com a janela do intérprete visível durante toda a transmissão.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO servico (titulo, descricao, criado_em, atualizado_em) VALUES
('Tradução para Libras de vídeos (janela de Libras)',
 'Tradução de vídeos institucionais, campanhas, cursos, aulas gravadas e conteúdo para redes sociais, com janela de Libras posicionada e dimensionada para leitura confortável.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO servico (titulo, descricao, criado_em, atualizado_em) VALUES
('Legendagem para surdos e ensurdecidos (LSE)',
 'Legendas que trazem, além das falas, a identificação de quem fala, efeitos sonoros e música — o que a pessoa surda ou com deficiência auditiva precisa para entender o vídeo por completo.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO servico (titulo, descricao, criado_em, atualizado_em) VALUES
('Audiodescrição',
 'Narração das informações visuais de vídeos, espetáculos, exposições e eventos para pessoas cegas ou com baixa visão.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO servico (titulo, descricao, criado_em, atualizado_em) VALUES
('Consultoria em acessibilidade comunicacional',
 'Planejamos com você a acessibilidade de eventos, projetos culturais e conteúdos digitais desde o início, de acordo com a Lei Brasileira de Inclusão — incluindo os recursos exigidos em editais e leis de incentivo à cultura.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO servico (titulo, descricao, criado_em, atualizado_em) VALUES
('Palestras e formações sobre inclusão',
 'Conversas e capacitações para empresas, escolas e equipes sobre acessibilidade, cultura surda, Libras e como comunicar sem deixar ninguém de fora.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
