-- Cadastro de intérpretes (uso interno do painel; nada aqui é exibido no site).
CREATE TABLE interprete (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(200) NOT NULL,
    data_nascimento   DATE         NOT NULL,
    endereco          VARCHAR(300) NOT NULL,
    email             VARCHAR(200),
    celular           VARCHAR(20)  NOT NULL,
    celular_whatsapp  BOOLEAN      NOT NULL,
    foto              VARCHAR(60),             -- nome do arquivo na pasta privada (APP_PRIVADO_DIR)
    criado_em         TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_interprete_nome ON interprete (nome);
