-- Perguntas frequentes do site, editáveis pelo painel.
-- Os textos iniciais são os que antes ficavam fixos no código (frontend/src/app/core/seo.ts).
CREATE TABLE pergunta (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pergunta       VARCHAR(300)  NOT NULL,
    resposta       VARCHAR(3000) NOT NULL,
    criado_em      TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em  TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO pergunta (pergunta, resposta, criado_em, atualizado_em) VALUES
('Como contratar um intérprete de Libras para o meu evento?',
 'Entre em contato com a gente pelo WhatsApp ou pelo formulário deste site. Conte a data, o horário, a duração, o local (ou a plataforma, se for online) e o tipo de evento, e a gente conversa sobre o número de profissionais de Libras necessários.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO pergunta (pergunta, resposta, criado_em, atualizado_em) VALUES
('Qual a diferença entre tradução e interpretação em Libras?',
 'A interpretação acontece ao vivo, de forma simultânea, enquanto a pessoa fala — como em palestras, aulas e lives. A tradução é feita sobre um conteúdo já pronto, como um vídeo gravado, com tempo para estudo e revisão.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO pergunta (pergunta, resposta, criado_em, atualizado_em) VALUES
('Por que eventos longos precisam de mais de um intérprete de Libras?',
 'A interpretação simultânea exige muita concentração física e mental. Em atividades mais longas, os intérpretes se revezam em intervalos curtos para manter a qualidade da tradução do início ao fim.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO pergunta (pergunta, resposta, criado_em, atualizado_em) VALUES
('Vocês atendem eventos online?',
 'Sim. Atendemos eventos presenciais e online, como lives, webinars e reuniões em Zoom, Microsoft Teams e Google Meet.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO pergunta (pergunta, resposta, criado_em, atualizado_em) VALUES
('Com quanta antecedência devo contratar?',
 'Quanto antes, melhor: a agenda de profissionais de Libras costuma ficar cheia em datas de muitos eventos. Enviar com antecedência o roteiro, os slides e os nomes próprios que serão citados ajuda os intérpretes a se prepararem.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO pergunta (pergunta, resposta, criado_em, atualizado_em) VALUES
('A acessibilidade em Libras é obrigatória?',
 'A Lei 10.436/2002 reconhece a Libras como meio legal de comunicação no Brasil, e a Lei Brasileira de Inclusão (Lei 13.146/2015) garante às pessoas com deficiência o acesso à informação e à comunicação. Na prática, órgãos públicos, instituições de ensino e muitos editais e leis de incentivo à cultura exigem recursos de acessibilidade como Libras, legendagem e audiodescrição.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO pergunta (pergunta, resposta, criado_em, atualizado_em) VALUES
('Que outros recursos de acessibilidade a Metonímia oferece?',
 'Além de Libras, oferecemos legendagem para surdos e ensurdecidos (LSE), audiodescrição para pessoas cegas ou com baixa visão e consultoria para tornar eventos, projetos culturais e conteúdos digitais acessíveis.',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
